apiVersion: v1
kind: Secret
metadata:
  name: stakefish-api-secret
type: Opaque
stringData:
  FISH_PG_HOST: {{ .Release.Name}}-postgresql:{{ .Values.postgresql.global.postgresql.service.ports.postgresql }}
  FISH_PG_USER: postgres
  FISH_PG_PASS: {{ .Values.postgresql.global.postgresql.auth.postgresPassword }}
  FISH_PG_DATABASE: {{ .Values.postgresql.global.postgresql.auth.database }}
  FISH_PG_API_ADDR: 0.0.0.0:{{ .Values.loadBalancerPort }}