apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    app: {{.Values.application.name}}
spec:
  ports:
  - port: {{ .Values.loadBalancerPort}}
    protocol: TCP
  selector:
    app: {{.Values.application.name}}
  type: LoadBalancer