apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: stakefish-api-secret
type: Opaque
stringData:
  FISH_PG_HOST: postgres-service:5432
  FISH_PG_USER: postgres
  FISH_PG_PASS: postgres
  FISH_PG_DATABASE: postgres
  FISH_PG_API_ADDR: 0.0.0.0:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14.1-alpine
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: postgres-secret
            
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakefish-api
  labels:
    app: stakefish-api
spec:
  selector:
    matchLabels:
      app: stakefish-api
  replicas: 1
  template:
    metadata:
      labels:
        app: stakefish-api
    spec:
      containers:
        - image: stakefish-api:0.1.0
          name: stakefish-api
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: stakefish-api-secret
            
          ports:
            - containerPort: 3000
              name: stakefish-api
---
apiVersion: v1
kind: Service
metadata:
 name: stakefish-api-service
spec:
 type: LoadBalancer
 selector:
   app: stakefish-api
 ports:
 - nodePort: 32410
   protocol: TCP
   port: 3000
   targetPort: 3000
