name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint with go-vet
        run: make lint

      - name: Test
        run: make test

      - name: Test Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false